
const product = [
    {
       // id: "1zJITDiC8_qRaXSDS7oUkVwbnCBprnkp0",
       id:1,
        imagesrc:"image/Hp.jpg",
        price: 899890,
        discount:"36%",
        category: "Hp",
        heading: "Hp 14s",
        
       description:"HP 14s (2020) is a Windows 10 Home laptop with a 14.00-inch display that has a resolution of 1920x1080 pixels. It is powered by a Core i3 processor and it comes with 4GB of RAM. The HP 14s (2020) packs 1TB of HDD storage.",
       display_size:"14.00 inch",
       display_resolution:"1920x1089 pixels",
       processor:"Corei3",
       ram:"4GB",
       os:"Windows 10 Home",
       hard_disk:"1TB",
       weight:"1.53kg"
             
    },
    {
       // id: "1G7sU0pcjZe3BL4SFuBZP_gqriN-4p78q",
       id:2,
       imagesrc:"image/Hp pavilion.jpg",
        price: 798900,
        discount:"40%",
        category: "Hp",
        heading: "Hp Pavilion",
        description:"HP Pavilion  is a Windows 10 Home laptop with a 15.60-inch display that has a resolution of 1920x1080 pixels. It is powered by a Core i5 processor and it comes with 16GB of RAM. The HP Pavilion 15-eg0103TX packs 512GB of SSD storage",
        display_size:"15.60 inch",
        display_resolution:"1920x1080 pixels",
       processor:"Corei5",
       ram:"16GB",
       os:"Windows 10 Home",
       hard_disk:"2TB",
       weight:"2.29kg"
      
    },
    {
       // id: "1A-oHFi8x1Q_y7kBMjx4VAkZBSEf372dF",
        id:3,
        imagesrc:"image/Hp Pavilion Aero.jpg",
        price: 899999,
        discount:"50%",
        category: "Hp",
        heading: "Hp Pavilion Aero",   
        description:"HP Pavilion Aero 13 is a Windows 10 laptop with a 13.30-inch display that has a resolution of 2560x1600 pixels. It is powered by a Ryzen 5000 Series processor and it comes with 16GB of RAM. The HP Pavilion Aero 13 packs 512GB of SSD storage.",
        display_size:"13.30 inch",
        display_resolution:"2560X1600 pixels",
       processor:"Ryzen 5000 Series",
       ram:"16GB",
       os:"Windows 10",
       hard_disk:"No",
       weight:"less than 1kg"
    },
    {
       // id:"1N4-S0nz39ThwfOCg-q6bSuukuTvSXUHO",
       id:4,
       imagesrc:"image/Hp Envy.jpg",
        price: 688880,
        discount:"20%",
        category: "Hp",
        heading: "Hp Envy",
        description:"HP Envy 14-eb0021TX is a Windows 10 Home laptop with a 14.00-inch display that has a resolution of 1920x1200 pixels. It is powered by a Core i7 processor and it comes with 16GB of RAM. The HP Envy 14-eb0021TX packs 1TB of SSD storage.",
        display_size:"14.00 inch",
        display_resolution:"1920X1200 pixels",
       processor:"Core i7",
       ram:"16GB",
       os:"Windows 10 Home",
       hard_disk:"No",
       weight:"1.49kg"
       
    },
    {
      //  id: "1D88tjRGveR3rb2By1lSVr7JQ8yjtH7oe",
        id:5,
        imagesrc:"image/Hp 15s Du3047tx.jpg",
        price: 599999,
        discount:"10%",
        category: "Hp",
        heading: "Hp 15s",
        description:"HP Notebook 15-da0295tu is a Windows 10 laptop with a 15.60-inch display that has a resolution of 768x1366 pixels. It is powered by a Pentium processor and it comes with 4GB of RAM. The HP Notebook 15-da0295tu packs 1TB of HDD storage.",
        display_size:"15.60 inch",
        display_resolution:"768X1366 pixels",
       processor:"Pentium",
       ram:"4GB",
       os:"Windows 10",
       hard_disk:"1TB",
       weight:"2.10kg" 
       
    },
    {
      //  id: "1D88tjRGveR3rb2By1lSVr7JQ8yjtH7oe",
        id:6,
        imagesrc:"image/HpEliteBook.jpg",
        price: 799999,
        discount:"20%",
        category: "Hp",
        heading: "Hp Elitebook",
        description:"The HP EliteBook is HP's flagship product aimed at the business market. The casing of the HP EliteBook is protected against scratches and can take a beating. In addition, an EliteBook has a matte screen, spill-resistant keyboard, and good security options such as a fingerprint sensor and a TPM security chip. HP EliteBooks are durable, have a long technical lifespan, and come with a good warranty",
        display_size:"17.60 inch",
        display_resolution:"868X1066 pixels",
       processor:"Core i5",
       ram:"8GB",
       os:"Windows 10",
       hard_disk:"256GB",
       weight:"1.10kg" 
       
    },
    {
      //  id: "1D88tjRGveR3rb2By1lSVr7JQ8yjtH7oe",
        id:7,
        imagesrc:"image/HpEssential.jpg",
        price: 699999,
        discount:"40%",
        category: "Hp",
        heading: "Hp Essential",
        description:"HP has clearly divided their assortment according to use. An HP Pavilion is more than sufficient for simple tasks such as surfing the web, sending emails, or browsing social media",
        display_size:"14.60 inch",
        display_resolution:"999X1366 pixels",
       processor:"Core i6",
       ram:"4GB",
       os:"Windows 10 Home",
       hard_disk:"500GB",
       weight:"2.00kg" 
       
    },
    {
      //  id: "1D88tjRGveR3rb2By1lSVr7JQ8yjtH7oe",
        id:8,
        imagesrc:"image/Hpspectre.jpg",
        price: 999999,
        discount:"70%",
        category: "Hp",
        heading: "Hp Spectra",
        description:"The HP Spectre is a striking laptop with high-quality specifications, like an SSD and a fast Intel Core processor. Thanks to the brushed aluminum, the Spectre has a durable casing. If you opt for the Spectre x360, you'll have both a laptop and a tablet in one package.",
        display_size:"13.5 inch",
        display_resolution:"999X999 pixels",
       processor:"Core i7",
       ram:"16GB",
       os:"Windows 10 Home",
       hard_disk:"250GB",
       weight:"1.10kg" 
       
    },
    {
        //id: "13B2bln-5C4RePT_dSCYsjLxNYhAJUW5I",
        id:9,
        imagesrc:"image/Apple.jpg",
        price: 899999,
        discount:"20%",
        category: "Apple",
        heading: "Apple MacBook",
        description:"Apple MacBook A1534 is a macOS laptop with a 12.00-inch display that has a resolution of 2304x1440 pixels. It is powered by a Core m5 processor and it comes with 8GB of RAM. The Apple MacBook A1534 packs 512GB of HDD storage and 256GB of SSD storage.",
        display_size:"12.00 inch",
        display_resolution:"2304X1440 pixels",
       processor:"Core m5",
       ram:"8GB",
       os:"macOS",
       hard_disk:"512GB",
       weight:"Intel Integrated" 
    },
    {
        //id: "13B2bln-5C4RePT_dSCYsjLxNYhAJUW5I",
        id:10,
        imagesrc:"image/Apple Mackbook Air.jpg",
        price: 599999,
        discount:"20%",
        category: "Apple",
        heading: "Apple MacBook",
        description:"Apple MacBook Air (M1, 2020) is a macOS laptop with a 13.30-inch display that has a resolution of 2560x1600 pixels. it comes with 8GB of RAM. The Apple MacBook Air (M1, 2020) packs 512GB of SSD storage.",
        display_size:"13.30 inch",
        display_resolution:"2560X1600 pixels",
       processor:"Core m5",
       ram:"8GB",
       os:"macOS",
       hard_disk:"No",
       weight:"1.29kg" 
    },
    {
        //id: "13B2bln-5C4RePT_dSCYsjLxNYhAJUW5I",
        id:11,
        imagesrc:"image/Apple MacBook Pro.jpg",
        price: 299999,
        discount:"40%",
        category: "Apple",
        heading: "Apple MacBook Pro",
        description:"Apple MacBook Pro   is a macOS laptop with a 13.30-inch display that has a resolution of 1600x2560 pixels. It is powered by a Core i5 processor and it comes with 8GB of RAM. The Apple MacBook Pro 13-inch 2020 packs 256GB of SSD storage.",
        display_size:"13.30 inch",
        display_resolution:"1600X2560 pixels",
       processor:"Core i5",
       ram:"8GB",
       os:"macOS",
       hard_disk:"256GB",
       weight:"1.40kg" 
       
    },
    {
        //id: "13B2bln-5C4RePT_dSCYsjLxNYhAJUW5I",
        id:12,
        imagesrc:"image/Apple MacBook Pro 13-inch 2020.jpg",
        price: 199999,
        discount:"20%",
        category: "Apple",
        heading: "Apple MacBook Pro 13",
        description:"Apple MacBook Pro 13-inch 2020 is a macOS laptop with a 14.20-inch display that has a resolution of 3024x1964 pixels. It is powered by a Apple M1 Pro processor and it comes with 16GB of RAM. The Apple MacBook Pro 14-inch 2021 packs 512GB of SSD storage.",
        display_size:"14.20 inch",
        display_resolution:"3024X1964 pixels",
       processor:"Apple M1 Pro",
       ram:"16GB",
       os:"macOS",
       hard_disk:"512GB",
       weight:"1.60kg" 
    },
    {
        //id: "13B2bln-5C4RePT_dSCYsjLxNYhAJUW5I",
        id:13,
        imagesrc:"image/Apple MacBook  pro12.jpg",
        price: 599999,
        discount:"60%",
        category: "Apple",
        heading: "Apple MacBook pro12",
        description:"Apple MacBook Pro 12 is a macOS laptop with a 13.30-inch display. It is powered by a Core i5 processor and it comes with 4GB of RAM. The Apple MacBook Pro A1278 packs 500GB of HDD storage.",
        display_size:"13.30 inch",
        display_resolution:"1024X2064 pixels",
       processor:"Apple  MacBook pro12",
       ram:"4GB",
       os:"macOS",
       hard_disk:"500GB",
       weight:"1.20kg" 
    },
    {
      //id: "13B2bln-5C4RePT_dSCYsjLxNYhAJUW5I",
      id:14,
      imagesrc:"image/AppleMpxQ2.jpg",
      price: 599999,
      discount:"60%",
      category: "Apple",
      heading: "Apple MacBook MpxQ2",
      description:"Apple MacBook Pro MPXQ2/R2 is a macOS laptop with a 13.30-inch display that has a resolution of 2560x1600 pixels. It is powered by a Core i5 processor and it comes with 8GB of RAM. The Apple MacBook Pro MPXQ2/R2 packs 128GB of SSD storage.",
      display_size:"13.30 inch",
      display_resolution:"2560X1600 pixels",
     processor:"Core i5",
     ram:"8GB",
     os:"macOs",
     hard_disk:"128GB",
     weight:"1.37kg" 
  },
  {
   //id: "13B2bln-5C4RePT_dSCYsjLxNYhAJUW5I",
   id:15,
   imagesrc:"image/AppleMacBookAirA1466.jpg",
   price: 499999,
   discount:"80%",
   category: "Apple",
   heading: "Apple MacBook AirA1466",
   description:"Apple MacBook Air A1466 is a macOS laptop with a 13.30-inch display that has a resolution of 1440x900 pixels. It is powered by a Core i5 processor and it comes with 4GB of RAM. The Apple MacBook Air A1466 packs 128GB of SSD storage.",
   display_size:"13.30 inch",
   display_resolution:"1440x900 pixels",
  processor:"Core i5",
  ram:"4GB",
  os:"macOs",
  hard_disk:"123GB",
  weight:"1.35kg" 
},
{
   //id: "13B2bln-5C4RePT_dSCYsjLxNYhAJUW5I",
   id:16,
   imagesrc:"image/Ideapad chromebook.jpg",
   price: 599999,
   discount:"80%",
   category: "Lenovo",
   heading: "Lenovo chromebook",
   description:"Lenovo ChromeBook S330 is a Chrome OS laptop with a 14.00-inch display that has a resolution of 1366x768 pixels. it comes with 4GB of RAM. The Lenovo ChromeBook S330 packs 64GB of HDD storage",
   display_size:"14.00 inch",
   display_resolution:"1366x768 pixels",
  processor:"Core i8",
  ram:"4GB",
  os:"Chrome OS",
  hard_disk:"64GB",
  weight:"1.50kg" 
},
{
   //id: "13B2bln-5C4RePT_dSCYsjLxNYhAJUW5I",
   id:17,
   imagesrc:"image/Ideapad Flex.jpg",
   price: 999999,
   discount:"90%",
   category: "Lenovo",
   heading: "Lenovo Flex",
   description:"Lenovo IdeaPad Flex 6 is a Windows 10 Home laptop with a 14.00-inch display that has a resolution of 1366x768 pixels. It is powered by a Ryzen 5 processor and it comes with 8GB of RAM. The Lenovo IdeaPad Flex 6 packs 256GB of HDD storage.",
   display_size:"15.00 inch",
   display_resolution:"1300x768 pixels",
  processor:"Ryzen 5",
  ram:"8GB",
  os:"Window 10 Home",
  hard_disk:"256GB",
  weight:"2.22kg" 
},
{
   //id: "13B2bln-5C4RePT_dSCYsjLxNYhAJUW5I",
   id:18,
   imagesrc:"image/lenovo gaming.jpg",
   price: 999999,
   discount:"90%",
   category: "Lenovo",
   heading: "Lenovo Gaming",
   description:"Lenovo IdeaPad Gaming 3i is a Windows 10 Home laptop with a 15.60-inch display that has a resolution of 1920x1080 pixels. It is powered by a Core i7 processor and it comes with 8GB of RAM. The Lenovo IdeaPad Gaming 3i packs 512GB of SSD storage.",
   display_size:"15.60 inch",
   display_resolution:"1920x1080 pixels",
  processor:"Core i7",
  ram:"8GB",
  os:"Window 10 Home",
  hard_disk:"No",
  weight:"2.25kg" 
},
{
   //id: "13B2bln-5C4RePT_dSCYsjLxNYhAJUW5I",
   id:19,
   imagesrc:"image/lenovo Ideapad.jpg",
   price: 199999,
   discount:"80%",
   category: "Lenovo",
   heading: "Lenovo Ideapad",
   description:"Lenovo IdeaPad Duet 3 is a Windows 10 laptop with a 10.23-inch display that has a resolution of 1920x1200 pixels. It is powered by a Celeron processor and it comes with 4GB of RAM. The Lenovo IdeaPad Duet 3 packs 128GB of SSD storage.",
   display_size:"10.23 inch",
   display_resolution:"1920x1200 pixels",
  processor:"Celeron",
  ram:"4GB",
  os:"Window 10 Home",
  hard_disk:"128GB",
  weight:"0.86kg" 
},
{
   //id: "13B2bln-5C4RePT_dSCYsjLxNYhAJUW5I",
   id:19,
   imagesrc:"image/lenovo slim5 pro.jpg",
   price: 499999,
   discount:"30%",
   category: "Lenovo",
   heading: "Lenovo slim5 pro",
   description:"Lenovo IdeaPad Slim 5 Pro (AMD) is a Windows 10 Home laptop with a 14.00-inch display that has a resolution of 2240x1400 pixels. It is powered by a Ryzen processor and it comes with 8GB of RAM. The Lenovo IdeaPad Slim 5 Pro (AMD) packs 512GB of SSD storage.",
   display_size:"14.00 inch",
   display_resolution:"2240x1400 pixels",
  processor:"Ryzen",
  ram:"8GB",
  os:"Window 10 Home",
  hard_disk:"512GB",
  weight:"1.38kg" 
},
{
   //id: "13B2bln-5C4RePT_dSCYsjLxNYhAJUW5I",
   id:20,
   imagesrc:"image/lenovoyoga.jpg",
   price: 299999,
   discount:"20%",
   category: "Lenovo",
   heading: "Lenovo yoga",
   description:"Lenovo Yoga 6 is a Windows 10 Home laptop with a 13.30-inch display that has a resolution of 1920x1080 pixels. it comes with 16GB of RAM. The Lenovo Yoga 6 packs 1TB of SSD storage.",
   display_size:"13.30 inch",
   display_resolution:"1920x1080 pixels",
  processor:"Core i9",
  ram:"16GB",
  os:"Window 10 Home",
  hard_disk:"1TB",
  weight:"1.32kg" 
},
{
   //id: "13B2bln-5C4RePT_dSCYsjLxNYhAJUW5I",
   id:20,
   imagesrc:"image/lenovothinkbook.jpg",
   price: 899999,
   discount:"90%",
   category: "Lenovo",
   heading: "Lenovo ThinkPad",
   description:"Lenovo ThinkPad N23 is a laptop with a 11.60-inch display that has a resolution of 1366x768 pixels. It is powered by a Celeron Dual Core processor and it comes with 4GB of RAM. The Lenovo ThinkPad N23 packs 128GB of SSD storage.",
   display_size:"11.60 inch",
   display_resolution:"1366x768 pixels",
  processor:"Celeron Dual Core",
  ram:"4GB",
  os:"Window 10",
  hard_disk:"No",
  weight:"1.40kg" 
}

]
export default product;